(()=>{
const workout=document.getElementById('workout'); if(!workout)return;
const PROTEIN_TARGET=160;
const plans=[
{name:'Sunday — Recovery + Core',cardio:'20 min easy Skillmill walk',moves:[['McGill curl-up','2 × 5 reps with 10-sec holds',45,'body'],['Bird dog','2 × 6 each side, slow',45,'body'],['Side plank','2 × 15–30 sec each side',45,'body'],['Hip / hamstring mobility','8–10 min',30,'body'],['Full-body stretch','8–10 min easy, pain-free',30,'body']]},
{name:'Monday — PUSH • Strength',cardio:'10 min easy/moderate Skillmill after lifting',moves:[['Machine or dumbbell chest press','4 × 6–8',150,'load'],['Incline dumbbell press','3 × 8–10',120,'load'],['Seated machine shoulder press','3 × 6–10',120,'load'],['Cable / lateral raise','3 × 12–15',60,'load'],['Cable triceps pressdown','3 × 10–12',75,'load'],['Dead bug','3 × 6 each side, slow',45,'body'],['Pallof press','2 × 10 each side',45,'load'],['Post-workout stretch','6–8 min chest, shoulders, hips',30,'body']]},
{name:'Tuesday — PULL • Strength',cardio:'15 min easy/moderate Skillmill after lifting',moves:[['Neutral-grip lat pulldown','4 × 6–10',120,'load'],['Chest-supported row','4 × 6–10',120,'load'],['Single-arm cable row','3 × 10 each side',90,'load'],['Reverse pec deck','3 × 12–15',60,'load'],['Dumbbell or cable curl','3 × 8–12',75,'load'],['Bird dog','3 × 6 each side, slow',45,'body'],['Side plank','2 × 15–30 sec each side',45,'body'],['Post-workout stretch','6–8 min lats, upper back, hips',30,'body']]},
{name:'Wednesday — LEGS • Quad Focus',cardio:'10 min easy Skillmill after lifting',moves:[['Leg press — controlled depth','4 × 8–12',150,'load'],['Dumbbell split squat','3 × 8–10 each side',120,'load'],['Leg extension','3 × 10–15',75,'load'],['Seated or lying leg curl','3 × 10–15',75,'load'],['Calf raise','4 × 10–15',60,'load'],['McGill curl-up','2 × 5 reps with 10-sec holds',45,'body'],['Pallof press','2 × 10 each side',45,'load'],['Post-workout stretch','8 min quads, hamstrings, glutes, hips',30,'body']]},
{name:'Thursday — PUSH • Size',cardio:'15 min easy/moderate Skillmill after lifting',moves:[['Incline machine or dumbbell press','4 × 8–12',120,'load'],['Machine chest press','3 × 10–12',90,'load'],['Cable fly','3 × 12–15',60,'load'],['Lateral raise','4 × 12–20',60,'load'],['Rope pressdown','3 × 10–15',60,'load'],['Overhead cable triceps extension','2 × 12–15',60,'load'],['Dead bug','2 × 8 each side',45,'body'],['Post-workout stretch','6–8 min chest, shoulders, triceps',30,'body']]},
{name:'Friday — PULL • Size',cardio:'20 min easy/moderate Skillmill after lifting',moves:[['Lat pulldown','4 × 8–12',120,'load'],['Chest-supported row','4 × 8–12',120,'load'],['Straight-arm pulldown','3 × 12–15',60,'load'],['Rear-delt fly','3 × 15–20',60,'load'],['Incline or preacher curl','3 × 10–12',60,'load'],['Hammer curl','2 × 12–15',60,'load'],['Bird dog','2 × 8 each side',45,'body'],['Post-workout stretch','6–8 min lats, biceps, upper back',30,'body']]},
{name:'Saturday — LEGS • Posterior + Shoulders',cardio:'10 min easy Skillmill after lifting',moves:[['Hip thrust or glute bridge','4 × 8–12',120,'load'],['Leg curl','4 × 8–12',90,'load'],['Supported reverse lunge','3 × 8–10 each side',120,'load'],['Leg extension','2 × 12–15',60,'load'],['Seated calf raise','4 × 12–15',60,'load'],['Machine or dumbbell lateral raise','3 × 12–20',60,'load'],['Pallof press','2 × 10 each side',45,'load'],['Post-workout stretch','8 min hamstrings, glutes, hips, shoulders',30,'body']]}
];
const css=document.createElement('style');css.textContent=`
.fitnav{display:flex;gap:8px;margin:10px 0}.fitnav button{flex:1;border:0;border-radius:999px;padding:10px;background:#e5e7eb;font-weight:900}.fitnav .active{background:#b58b38;color:#111}.wgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.wfield{font-size:12px;font-weight:800}.wfield input,.wfield select{width:100%;padding:10px;border:1px solid #d1d5db;border-radius:10px;margin-top:6px;font:inherit}.wmove{width:100%}.wname{font-weight:800;font-size:16px}.wpres{font-size:13px;margin-top:2px}.wcoach{font-size:12px;color:#6b7280;margin:6px 0}.setrows{display:grid;gap:7px;margin:9px 0}.setrow{display:grid;grid-template-columns:42px 1fr 1fr;gap:7px;align-items:center}.setrow b{font-size:12px;color:#6b7280}.setrow input{width:100%;padding:9px;border:1px solid #d1d5db;border-radius:9px}.wrest{border:0;border-radius:10px;padding:9px 12px;background:#273244;color:#fff;font-weight:800}.wclock{font-weight:900;color:#b58b38;margin-left:8px}.wcomplete{border:0;border-radius:10px;padding:13px;background:#b58b38;color:#111;font-weight:900;width:100%}.wdaytabs{display:flex;gap:7px;overflow:auto;margin:10px 0}.wdaytabs button{border:0;border-radius:999px;padding:7px 10px;background:#e5e7eb;white-space:nowrap}.wdaytabs .active{background:#b58b38}.wdone .wname{text-decoration:line-through;color:#9ca3af}.proteinBox{display:grid;grid-template-columns:1fr 1fr;gap:10px}.proteinBig{font-size:30px;font-weight:950}.proteinAdd{display:flex;gap:8px;margin-top:8px}.proteinAdd input{flex:1;min-width:0;padding:10px;border:1px solid #d1d5db;border-radius:10px}.proteinAdd button{border:0;border-radius:10px;background:#273244;color:white;font-weight:900;padding:10px 14px}.proteinEntries{font-size:12px;color:#6b7280;margin-top:8px}.dashStats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.dashStat{background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:12px}.dashStat b{font-size:22px;display:block}.historyRow{padding:10px 0;border-bottom:1px solid #eee}.historyRow:last-child{border-bottom:0}.pr{display:inline-block;background:#fff6db;border:1px solid #ead08b;border-radius:999px;padding:3px 7px;font-size:11px;font-weight:900;margin-left:6px}.photoTriples{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.photoPair{display:grid;grid-template-columns:1fr 1fr;gap:5px}.photoPair img{width:100%;aspect-ratio:3/4;object-fit:cover;border-radius:8px;background:#eee}.photoTitle{font-size:11px;font-weight:900;margin:5px 0}.photoUpload{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.photoUpload label{font-size:12px;font-weight:900}.photoUpload input{width:100%;font-size:11px;margin-top:4px}.coachBox{background:#fff6db;border:1px solid #ead08b;border-radius:12px;padding:12px;line-height:1.45}.goalLine{font-size:13px;margin-top:6px}.mini{font-size:11px;color:#6b7280}@media(max-width:650px){.wgrid,.proteinBox,.dashStats{grid-template-columns:1fr 1fr}.photoTriples,.photoUpload{grid-template-columns:1fr}.photoPair{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(css);
const today=new Date();let selected=today.getDay();let fitnessView='workout';let state={};let timer=null;const $=id=>document.getElementById(id);const iso=d=>d.toISOString().slice(0,10);const dateKey=()=>iso(new Date());const storeKey=()=>`ascend-workout-${dateKey()}-${selected}`;const fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
const range=txt=>{const m=txt.match(/(\d+)\s*[–-]\s*(\d+)/);return m?[+m[1],+m[2]]:null};const setCount=txt=>{const m=txt.match(/^(\d+)\s*[×x]/);return m?+m[1]:1};
workout.innerHTML=`<div class="hero"><div class="eyebrow">ASCEND FITNESS</div><h1>Build Size. Build Strength.</h1><div class="goalLine"><b>Long-term:</b> 185 lb at about 14% body fat • flat/tight waist • stronger and bigger</div><div class="goalLine"><b>Current 6-month phase:</b> build meaningful muscle and strength while keeping the waist controlled; do not force the scale.</div></div><div class="fitnav"><button id="fitWorkoutBtn" class="active">Today's Workout</button><button id="fitDashBtn">Dashboard</button></div><div id="fitWorkoutPane"></div><div id="fitDashPane" hidden></div>`;
function workoutPane(){return `<div class="wdaytabs" id="wDays"></div><div class="card"><div class="wgrid"><label class="wfield">Daily weigh-in (lb)<input id="wWeight" type="number" inputmode="decimal" step="0.1" placeholder="144.8"></label><div><div class="mini">Protein remaining today</div><div class="proteinBig"><span id="proteinRemain">${PROTEIN_TARGET}</span>g</div><div class="mini">of ${PROTEIN_TARGET}g target</div></div></div><div class="proteinAdd"><input id="proteinAddInput" type="number" inputmode="numeric" min="1" placeholder="Add protein grams"><button id="proteinAddBtn">+ Add</button></div><div id="proteinEntries" class="proteinEntries"></div></div><div id="wMoves"></div><div class="card"><div class="eyebrow">Daily Cardio</div><h3>🔥 Skillmill</h3><p id="wCardioText"></p><label class="wfield">Minutes completed<input id="wCardioMin" type="number" inputmode="numeric" placeholder="Minutes"></label><div class="task"><input id="wCardioDone" type="checkbox"><span>Cardio complete</span></div></div><div class="card" id="wPhotoCard" hidden><div class="eyebrow">End-of-Week Check-In</div><h3>📸 Front • Side • Back</h3><p class="muted">Use the same lighting, distance and pose each week.</p><div class="photoUpload"><label>Front<input id="wPhotoFront" type="file" accept="image/*" capture="user"></label><label>Side<input id="wPhotoSide" type="file" accept="image/*" capture="user"></label><label>Back<input id="wPhotoBack" type="file" accept="image/*" capture="user"></label></div><div id="wPhotoStatus" class="muted" style="margin-top:8px"></div><div id="wCompare" hidden><label class="wfield">Compare this week to<select id="wCompareSelect"></select></label><div id="wPhotoCompare"></div></div></div><div class="card"><div class="eyebrow">Weekly Coaching</div><div id="wCoach" class="coachBox"></div><button id="wComplete" class="wcomplete" style="margin-top:12px">Complete Today's Workout</button></div>`}
$('fitWorkoutPane').innerHTML=workoutPane();
$('fitWorkoutBtn').onclick=()=>switchFit('workout');$('fitDashBtn').onclick=()=>switchFit('dash');
function switchFit(v){fitnessView=v;$('fitWorkoutBtn').classList.toggle('active',v==='workout');$('fitDashBtn').classList.toggle('active',v==='dash');$('fitWorkoutPane').hidden=v!=='workout';$('fitDashPane').hidden=v!=='dash';if(v==='dash')renderDashboard()}
function allWorkoutStates(){const rows=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!k.startsWith('ascend-workout-'))continue;try{const s=JSON.parse(localStorage.getItem(k));const m=k.match(/^ascend-workout-(\d{4}-\d{2}-\d{2})-(\d)$/);if(m&&s)rows.push({key:k,date:m[1],day:+m[2],...s})}catch{}}return rows.sort((a,b)=>a.date.localeCompare(b.date))}
function previousSets(moveName){const rows=allWorkoutStates().filter(r=>r.logs&&r.logs[moveName]&&r.logs[moveName].sets?.length);return rows.length?rows[rows.length-1].logs[moveName].sets:[]}
function bestSet(moveName){let best=null;allWorkoutStates().forEach(r=>{const l=r.logs&&r.logs[moveName];(l?.sets||[]).forEach(s=>{const w=+s.weight||0, reps=+s.reps||0;if(!w||!reps)return;const score=w*(1+reps/30);if(!best||score>best.score)best={weight:w,reps,score,date:r.date}})});return best}
function coach(move){if(move[3]!=='load')return 'Complete this with controlled form. Stop if it creates sharp or radiating pain.';const r=range(move[1]),sets=previousSets(move[0]);if(!r||!sets.length)return 'Log every work set. Build reps first, then load.';const valid=sets.filter(s=>+s.weight&&+s.reps);if(!valid.length)return 'Log every work set. Build reps first, then load.';const same=valid.every(s=>+s.weight===+valid[0].weight),allTop=valid.length>=setCount(move[1])&&valid.every(s=>+s.reps>=r[1]);if(same&&allTop)return `Last session: ${valid[0].weight} lb across ${valid.length} sets, all at ${r[1]}+ reps. If form was clean, increase the smallest practical amount today and restart near ${r[0]} reps.`;const best=Math.max(...valid.map(s=>+s.reps));return `Last session best: ${valid[0].weight||'—'} lb × ${best}. Keep the load until every work set reaches the top of the ${r[0]}–${r[1]} range cleanly.`}
function save(){localStorage.setItem(storeKey(),JSON.stringify(state));updateCoach()}
function render(){state=JSON.parse(localStorage.getItem(storeKey())||'{"logs":{},"proteinEntries":[]}');if(!state.logs)state.logs={};if(!state.proteinEntries)state.proteinEntries=[];const p=plans[selected];$('wWeight').value=state.weight||'';$('wCardioText').textContent=p.cardio;$('wCardioMin').value=state.cardioMin||'';$('wCardioDone').checked=!!state.cardioDone;$('wPhotoCard').hidden=selected!==0;$('wDays').innerHTML=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<button class="${i===selected?'active':''}" data-day="${i}">${d}</button>`).join('');$('wDays').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=+b.dataset.day;render()});
$('wMoves').innerHTML=p.moves.map(m=>{const l=state.logs[m[0]]||{};const n=setCount(m[1]);const sets=l.sets||[];const setHtml=m[3]==='load'?`<div class="setrows">${Array.from({length:n},(_,i)=>`<div class="setrow" data-set="${i}"><b>Set ${i+1}</b><input class="wwgt" inputmode="decimal" placeholder="Weight" value="${sets[i]?.weight||''}"><input class="wreps" inputmode="numeric" placeholder="Reps" value="${sets[i]?.reps||''}"></div>`).join('')}</div>`:'';return `<div class="card ${l.done?'wdone':''}" data-move="${encodeURIComponent(m[0])}"><div class="task"><input class="wcheck" type="checkbox" ${l.done?'checked':''}><div class="wmove"><div class="wname">${m[0]}</div><div class="wpres">${m[1]}</div><div class="wcoach">${coach(m)}</div>${setHtml}<button class="wrest" data-sec="${m[2]}">Start ${fmt(m[2])} Rest</button><span class="wclock"></span></div></div></div>`}).join('');
document.querySelectorAll('[data-move]').forEach(card=>{const n=decodeURIComponent(card.dataset.move),log=state.logs[n]||(state.logs[n]={sets:[]});if(!log.sets)log.sets=[];card.querySelector('.wcheck').onchange=e=>{log.done=e.target.checked;card.classList.toggle('wdone',e.target.checked);save()};card.querySelectorAll('.setrow').forEach(row=>{const i=+row.dataset.set;log.sets[i]=log.sets[i]||{};row.querySelector('.wwgt').oninput=e=>{log.sets[i].weight=e.target.value;save()};row.querySelector('.wreps').oninput=e=>{log.sets[i].reps=e.target.value;save()}});card.querySelector('.wrest').onclick=e=>startRest(+e.target.dataset.sec,card.querySelector('.wclock'))});
renderProtein();$('wComplete').textContent=state.complete?'Workout Complete ✓':"Complete Today's Workout";updateCoach();if(selected===0)loadPhotoCompare()}
function startRest(sec,el){clearInterval(timer);let left=sec;el.textContent=fmt(left);timer=setInterval(()=>{left--;el.textContent=fmt(Math.max(left,0));if(left<=0){clearInterval(timer);el.textContent='GO';if(navigator.vibrate)navigator.vibrate([180,100,180]);setTimeout(()=>alert('Rest complete — start your next set.'),20)}},1000)}
function renderProtein(){const total=(state.proteinEntries||[]).reduce((a,b)=>a+(+b||0),0),remain=Math.max(PROTEIN_TARGET-total,0);$('proteinRemain').textContent=remain;$('proteinEntries').textContent=total?`Logged: ${total}g • entries: ${state.proteinEntries.join('g + ')}g`:''}
$('proteinAddBtn').onclick=()=>{const v=+$('proteinAddInput').value;if(v>0){state.proteinEntries.push(v);$('proteinAddInput').value='';save();renderProtein()}};$('proteinAddInput').onkeydown=e=>{if(e.key==='Enter')$('proteinAddBtn').click()};$('wWeight').oninput=e=>{state.weight=e.target.value;save()};$('wCardioMin').oninput=e=>{state.cardioMin=e.target.value;save()};$('wCardioDone').onchange=e=>{state.cardioDone=e.target.checked;save()};$('wComplete').onclick=()=>{state.complete=true;save();$('wComplete').textContent='Workout Complete ✓'};
function weightRows(){return allWorkoutStates().filter(r=>+r.weight).map(r=>({date:r.date,weight:+r.weight}))}
function avg(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:null}
function weeklyWeightCoach(){const rows=weightRows();const uniq=[];const seen=new Set();rows.slice().reverse().forEach(r=>{if(!seen.has(r.date)){seen.add(r.date);uniq.push(r)}});uniq.reverse();const latest=uniq.slice(-7).map(x=>x.weight),prior=uniq.slice(-14,-7).map(x=>x.weight);if(latest.length<4)return 'Keep logging your morning weight. Once there are enough entries, I’ll coach the trend instead of reacting to one day.';const a=avg(latest),b=avg(prior);if(!b)return `Current 7-day average: ${a.toFixed(1)} lb. Keep the routine consistent while we build a second week for comparison.`;const delta=a-b;if(delta<0.15)return `7-day average: ${a.toFixed(1)} lb (${delta>=0?'+':''}${delta.toFixed(1)} vs prior week). If this stays flat for 7–14 days and training is progressing, increase food modestly—about 150–200 calories/day.`;if(delta>1.0)return `7-day average: ${a.toFixed(1)} lb (+${delta.toFixed(1)} vs prior week). That is a fast jump. Keep protein high and watch the waist/weekly photos rather than pushing calories higher.`;return `7-day average: ${a.toFixed(1)} lb (+${delta.toFixed(1)} vs prior week). This is moving in the right direction; keep intake and training consistent.`}
function weeklyLiftCoach(){let earned=0,tracked=0;plans.flatMap(p=>p.moves).filter(m=>m[3]==='load').forEach(m=>{const r=range(m[1]),sets=previousSets(m[0]);if(!r||!sets.length)return;const valid=sets.filter(s=>+s.weight&&+s.reps);if(!valid.length)return;tracked++;if(valid.length>=setCount(m[1])&&valid.every(s=>+s.reps>=r[1]))earned++});return tracked?`${earned} exercise${earned===1?'':'s'} currently qualify for a load increase based on the last logged sets. Others should stay at the same load and beat reps first.`:'Start logging each set and I’ll identify exactly which lifts have earned more weight.'}
function updateCoach(){if(!$('wCoach'))return;$('wCoach').innerHTML=`<b>Bodyweight trend:</b> ${weeklyWeightCoach()}<br><br><b>Progressive overload:</b> ${weeklyLiftCoach()}<br><br><b>Rule:</b> clean reps first. No grinding through sharp/radiating back pain, numbness, weakness or abdominal pressure.`}
function weekKey(){const d=new Date();d.setHours(0,0,0,0);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return iso(d)}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open('ascend-fitness',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('photos'))r.result.createObjectStore('photos',{keyPath:'week'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getWeekPhoto(){const d=await db();const row=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').get(weekKey());r.onsuccess=()=>res(r.result||{week:weekKey(),photos:{}});r.onerror=()=>rej(r.error)});d.close();if(!row.photos)row.photos={front:row.blob||null};return row}
async function putPhoto(kind,file){const row=await getWeekPhoto();row.photos=row.photos||{};row.photos[kind]=file;row.created=Date.now();const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('photos','readwrite');tx.objectStore('photos').put(row);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}
async function allPhotos(){const d=await db();const rows=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.week.localeCompare(a.week)));r.onerror=()=>rej(r.error)});d.close();rows.forEach(r=>{if(!r.photos)r.photos={front:r.blob||null}});return rows}
function imgSrc(blob){return blob?URL.createObjectURL(blob):''}
async function loadPhotoCompare(){const rows=await allPhotos(),current=rows.find(x=>x.week===weekKey());const count=current?['front','side','back'].filter(k=>current.photos?.[k]).length:0;$('wPhotoStatus').textContent=count===3?'Front, side and back saved for this week ✓':`${count}/3 views saved this week.`;if(!current||count===0){$('wCompare').hidden=true;return}const older=rows.filter(x=>x.week!==weekKey()&&Object.values(x.photos||{}).some(Boolean));$('wCompare').hidden=false;if(!older.length){$('wCompareSelect').innerHTML='<option>No earlier weeks yet</option>';$('wPhotoCompare').innerHTML='<p class="muted">Your first comparison will appear after another week is saved.</p>';return}$('wCompareSelect').innerHTML=older.map((x,i)=>`<option value="${x.week}" ${i===0?'selected':''}>Week of ${x.week}${i===0?' — previous saved week':''}</option>`).join('');const show=wk=>{const old=older.find(r=>r.week===wk);$('wPhotoCompare').innerHTML=`<div class="photoTriples">${['front','side','back'].map(k=>`<div><div class="photoTitle">${k.toUpperCase()}</div><div class="photoPair"><img src="${imgSrc(old?.photos?.[k])}"><img src="${imgSrc(current.photos?.[k])}"></div><div class="mini">Older week ← → This week</div></div>`).join('')}</div>`};show(older[0].week);$('wCompareSelect').onchange=e=>show(e.target.value)}
['front','side','back'].forEach(k=>{$('wPhoto'+k[0].toUpperCase()+k.slice(1)).onchange=async e=>{const f=e.target.files&&e.target.files[0];if(!f)return;await putPhoto(k,f);await loadPhotoCompare()}});
function renderDashboard(){const rows=allWorkoutStates();const weights=weightRows();const uniq=[];const seen=new Set();weights.slice().reverse().forEach(r=>{if(!seen.has(r.date)){seen.add(r.date);uniq.push(r)}});const latest7=uniq.slice(0,7).map(x=>x.weight);const avg7=avg(latest7);const completed=rows.filter(r=>r.complete).length;const cardio=rows.filter(r=>r.cardioDone).length;const prs=[];const names=[...new Set(plans.flatMap(p=>p.moves.filter(m=>m[3]==='load').map(m=>m[0])))];names.forEach(n=>{const b=bestSet(n);if(b)prs.push({name:n,...b})});prs.sort((a,b)=>b.date.localeCompare(a.date));const recent=rows.slice(-12).reverse();$('fitDashPane').innerHTML=`<div class="card"><div class="eyebrow">Progress Dashboard</div><h2>185 / ~14% Long-Term Project</h2><div class="dashStats"><div class="dashStat"><span class="mini">Latest weight</span><b>${uniq[0]?.weight?.toFixed(1)||'—'}</b></div><div class="dashStat"><span class="mini">7-day average</span><b>${avg7?avg7.toFixed(1):'—'}</b></div><div class="dashStat"><span class="mini">Workouts completed</span><b>${completed}</b></div><div class="dashStat"><span class="mini">Cardio days logged</span><b>${cardio}</b></div></div></div><div class="card"><div class="eyebrow">Coach</div><div class="coachBox"><b>Weight:</b> ${weeklyWeightCoach()}<br><br><b>Lifting:</b> ${weeklyLiftCoach()}</div></div><div class="card"><div class="eyebrow">Personal Records</div><h3>Best Logged Sets</h3>${prs.length?prs.slice(0,12).map(p=>`<div class="historyRow"><b>${p.name}</b><span class="pr">PR</span><div class="muted">${p.weight} lb × ${p.reps} • ${p.date}</div></div>`).join(''):'<p class="muted">Your PR board will populate as you log sets.</p>'}</div><div class="card"><div class="eyebrow">Workout History</div><h3>Recent Sessions</h3>${recent.length?recent.map(r=>{const p=plans[r.day];const done=Object.values(r.logs||{}).filter(x=>x.done).length;return `<div class="historyRow"><b>${r.date} — ${p?.name||'Workout'}</b><div class="muted">${r.complete?'Completed ✓':'In progress'} • ${done} exercises checked • ${r.cardioDone?'Cardio ✓':'Cardio not checked'}</div></div>`}).join(''):'<p class="muted">No workout history yet.</p>'}</div><div class="card"><div class="eyebrow">Photo Progress</div><h3>Weekly Comparison</h3><p class="muted">Open Sunday in Today's Workout to add front, side and back photos and compare any saved week.</p></div>`}
render();
})();