(()=>{
const workout=document.getElementById('workout'); if(!workout)return;
const plans=[
{name:'Sunday — Recovery + Core',cardio:'20 min easy Skillmill walk',moves:[['McGill curl-up','2 × 5 reps with 10-sec holds',45],['Bird dog','2 × 6 each side, slow',45],['Side plank','2 × 15–30 sec each side',45],['Hip / hamstring mobility','8–10 min',30]]},
{name:'Monday — PUSH • Strength',cardio:'10 min easy/moderate Skillmill after lifting',moves:[['Machine or dumbbell chest press','4 × 6–8',150],['Incline dumbbell press','3 × 8–10',120],['Seated machine shoulder press','3 × 6–10',120],['Cable / lateral raise','3 × 12–15',60],['Cable triceps pressdown','3 × 10–12',75],['Dead bug','3 × 6 each side, slow',45],['Pallof press','2 × 10 each side',45]]},
{name:'Tuesday — PULL • Strength',cardio:'15 min easy/moderate Skillmill after lifting',moves:[['Neutral-grip lat pulldown','4 × 6–10',120],['Chest-supported row','4 × 6–10',120],['Single-arm cable row','3 × 10 each side',90],['Reverse pec deck','3 × 12–15',60],['Dumbbell or cable curl','3 × 8–12',75],['Bird dog','3 × 6 each side, slow',45],['Side plank','2 × 15–30 sec each side',45]]},
{name:'Wednesday — LEGS • Quad Focus',cardio:'10 min easy Skillmill after lifting',moves:[['Leg press — controlled depth','4 × 8–12',150],['Dumbbell split squat','3 × 8–10 each side',120],['Leg extension','3 × 10–15',75],['Seated or lying leg curl','3 × 10–15',75],['Calf raise','4 × 10–15',60],['McGill curl-up','2 × 5 reps with 10-sec holds',45],['Pallof press','2 × 10 each side',45]]},
{name:'Thursday — PUSH • Size',cardio:'15 min easy/moderate Skillmill after lifting',moves:[['Incline machine or dumbbell press','4 × 8–12',120],['Machine chest press','3 × 10–12',90],['Cable fly','3 × 12–15',60],['Lateral raise','4 × 12–20',60],['Rope pressdown','3 × 10–15',60],['Overhead cable triceps extension','2 × 12–15',60],['Dead bug','2 × 8 each side',45]]},
{name:'Friday — PULL • Size',cardio:'20 min easy/moderate Skillmill after lifting',moves:[['Lat pulldown','4 × 8–12',120],['Chest-supported row','4 × 8–12',120],['Straight-arm pulldown','3 × 12–15',60],['Rear-delt fly','3 × 15–20',60],['Incline or preacher curl','3 × 10–12',60],['Hammer curl','2 × 12–15',60],['Bird dog','2 × 8 each side',45]]},
{name:'Saturday — LEGS • Posterior + Shoulders',cardio:'10 min easy Skillmill after lifting',moves:[['Hip thrust or glute bridge','4 × 8–12',120],['Leg curl','4 × 8–12',90],['Supported reverse lunge','3 × 8–10 each side',120],['Leg extension','2 × 12–15',60],['Seated calf raise','4 × 12–15',60],['Machine or dumbbell lateral raise','3 × 12–20',60],['Pallof press','2 × 10 each side',45]]}
];
const css=document.createElement('style');css.textContent=`.wgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.wfield{font-size:12px;font-weight:800}.wfield input,.wfield select{width:100%;padding:10px;border:1px solid #d1d5db;border-radius:10px;margin-top:6px;font:inherit}.wmove{width:100%}.wname{font-weight:800;font-size:16px}.wpres{font-size:13px;margin-top:2px}.wcoach{font-size:12px;color:#6b7280;margin:6px 0}.wsetgrid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:8px 0}.wsetgrid input{width:100%;padding:9px;border:1px solid #d1d5db;border-radius:9px;margin:0}.wrest{border:0;border-radius:10px;padding:9px 12px;background:#273244;color:#fff;font-weight:800}.wclock{font-weight:900;color:#b58b38;margin-left:8px}.wcomplete{border:0;border-radius:10px;padding:13px;background:#b58b38;color:#111;font-weight:900;width:100%}.wdaytabs{display:flex;gap:7px;overflow:auto;margin:10px 0}.wdaytabs button{border:0;border-radius:999px;padding:7px 10px;background:#e5e7eb;white-space:nowrap}.wdaytabs .active{background:#b58b38}.wphoto-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.wphoto-grid img{width:100%;aspect-ratio:3/4;object-fit:cover;border-radius:12px;background:#eee}.wphoto-label{font-size:12px;font-weight:800;margin-bottom:5px}.wphoto-select{width:100%;padding:10px;border:1px solid #d1d5db;border-radius:10px;margin:8px 0}.wdone .wname{text-decoration:line-through;color:#9ca3af}@media(max-width:650px){.wgrid,.wphoto-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(css);
const today=new Date();let selected=today.getDay();const dateKey=()=>new Date().toISOString().slice(0,10);const storeKey=()=>`ascend-workout-${dateKey()}-${selected}`;let state={};let timer=null;
workout.innerHTML=`<div class="hero"><div class="eyebrow">ASCEND • 185 / 14 PROJECT</div><h1 id="wTitle"></h1><div>Size + strength • daily Skillmill • back-smart core</div></div><div class="wdaytabs" id="wDays"></div><div class="card"><div class="wgrid"><label class="wfield">Daily weigh-in (lb)<input id="wWeight" type="number" inputmode="decimal" step="0.1" placeholder="144.8"></label><label class="wfield">Protein today (g)<input id="wProtein" type="number" inputmode="numeric" placeholder="160"></label></div><p class="muted"><b>Protein target: 160 g.</b> Use your 7-day weight trend, not one weigh-in.</p></div><div id="wMoves"></div><div class="card"><div class="eyebrow">Daily Cardio</div><h3>🔥 Skillmill</h3><p id="wCardioText"></p><label class="wfield">Minutes completed<input id="wCardioMin" type="number" inputmode="numeric" placeholder="Minutes"></label><div class="task"><input id="wCardioDone" type="checkbox"><span>Cardio complete</span></div></div><div class="card" id="wPhotoCard" hidden><div class="eyebrow">Weekly Check-In</div><h3>📸 Progress Photo + Comparison</h3><p class="muted">Take the photo at the end of the week in the same lighting, distance and pose.</p><input id="wPhoto" type="file" accept="image/*" capture="user"><div id="wPhotoStatus" class="muted"></div><div id="wCompare" hidden><label class="wfield">Compare this week to<select id="wCompareSelect" class="wphoto-select"></select></label><div class="wphoto-grid"><div><div class="wphoto-label">Selected week</div><img id="wOldPhoto"></div><div><div class="wphoto-label">This week</div><img id="wNewPhoto"></div></div></div></div><div class="card"><div class="eyebrow">Progression Coach</div><p>Reach the top of the prescribed rep range on every work set with clean form and about 1–2 reps in reserve before increasing load. Typical jump: 2.5–5 lb upper body, 5–10 lb lower-body machines.</p><button id="wComplete" class="wcomplete">Complete Today's Workout</button></div>`;
const $=id=>document.getElementById(id);const fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;const range=txt=>{const m=txt.match(/(\d+)\s*[–-]\s*(\d+)/);return m?[+m[1],+m[2]]:null};
function previous(moveName){let best=null;for(let i=0;i<60;i++){const k=localStorage.key(i);if(!k||!k.startsWith('ascend-workout-'))continue;try{const s=JSON.parse(localStorage.getItem(k));if(s&&s.logs&&s.logs[moveName]&&s.logs[moveName].weight)best=s.logs[moveName]}catch{}}return best}
function coach(move){const r=range(move[1]),p=previous(move[0]);if(!r||!p)return 'Log weight and actual reps. Build reps first, then load.';const reps=+p.reps||0;if(reps>=r[1])return `Last: ${p.weight} lb × ${p.reps}. If all sets were clean, add the smallest available load and aim near ${r[0]} reps.`;return `Last: ${p.weight} lb × ${p.reps}. Keep the load and beat it by 1 rep while staying in ${r[0]}–${r[1]}.`}
function save(){localStorage.setItem(storeKey(),JSON.stringify(state))}
function render(){state=JSON.parse(localStorage.getItem(storeKey())||'{"logs":{}}');if(!state.logs)state.logs={};const p=plans[selected];$('wTitle').textContent=p.name;$('wCardioText').textContent=p.cardio;$('wPhotoCard').hidden=selected!==0;$('wWeight').value=state.weight||'';$('wProtein').value=state.protein||'';$('wCardioMin').value=state.cardioMin||'';$('wCardioDone').checked=!!state.cardioDone;$('wDays').innerHTML=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<button class="${i===selected?'active':''}" data-day="${i}">${d}</button>`).join('');$('wDays').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=+b.dataset.day;render()});$('wMoves').innerHTML=p.moves.map((m,i)=>{const l=state.logs[m[0]]||{};return `<div class="card ${l.done?'wdone':''}" data-move="${encodeURIComponent(m[0])}"><div class="task"><input class="wcheck" type="checkbox" ${l.done?'checked':''}><div class="wmove"><div class="wname">${m[0]}</div><div class="wpres">${m[1]}</div><div class="wcoach">${coach(m)}</div><div class="wsetgrid"><input class="wwgt" inputmode="decimal" placeholder="Working weight" value="${l.weight||''}"><input class="wreps" inputmode="numeric" placeholder="Actual reps" value="${l.reps||''}"></div><button class="wrest" data-sec="${m[2]}">Start ${fmt(m[2])} Rest</button><span class="wclock"></span></div></div></div>`}).join('');document.querySelectorAll('[data-move]').forEach(card=>{const n=decodeURIComponent(card.dataset.move),log=state.logs[n]||(state.logs[n]={});card.querySelector('.wcheck').onchange=e=>{log.done=e.target.checked;card.classList.toggle('wdone',e.target.checked);save()};card.querySelector('.wwgt').oninput=e=>{log.weight=e.target.value;save()};card.querySelector('.wreps').oninput=e=>{log.reps=e.target.value;save()};card.querySelector('.wrest').onclick=e=>startRest(+e.target.dataset.sec,card.querySelector('.wclock'))});if(selected===0)loadPhotoCompare()}
function startRest(sec,el){clearInterval(timer);let left=sec;el.textContent=fmt(left);timer=setInterval(()=>{left--;el.textContent=fmt(Math.max(left,0));if(left<=0){clearInterval(timer);el.textContent='GO';if(navigator.vibrate)navigator.vibrate([180,100,180]);setTimeout(()=>alert('Rest complete — start your next set.'),20)}},1000)}
$('wWeight').oninput=e=>{state.weight=e.target.value;save()};$('wProtein').oninput=e=>{state.protein=e.target.value;save()};$('wCardioMin').oninput=e=>{state.cardioMin=e.target.value;save()};$('wCardioDone').onchange=e=>{state.cardioDone=e.target.checked;save()};$('wComplete').onclick=()=>{state.complete=true;save();$('wComplete').textContent='Workout Complete ✓'};
function weekKey(){const d=new Date();d.setHours(0,0,0,0);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open('ascend-fitness',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('photos'))r.result.createObjectStore('photos',{keyPath:'week'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putPhoto(file){const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('photos','readwrite');tx.objectStore('photos').put({week:weekKey(),blob:file,created:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}
async function allPhotos(){const d=await db();const rows=await new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.week.localeCompare(a.week)));r.onerror=()=>rej(r.error)});d.close();return rows}
async function loadPhotoCompare(){const rows=await allPhotos();const current=rows.find(x=>x.week===weekKey());$('wPhotoStatus').textContent=current?'This week’s progress photo saved ✓':'No photo saved for this week yet.';if(!current){$('wCompare').hidden=true;return}const older=rows.filter(x=>x.week!==weekKey());$('wNewPhoto').src=URL.createObjectURL(current.blob);if(!older.length){$('wCompare').hidden=false;$('wCompareSelect').innerHTML='<option>No earlier weeks yet</option>';$('wOldPhoto').removeAttribute('src');return}$('wCompare').hidden=false;$('wCompareSelect').innerHTML=older.map((x,i)=>`<option value="${x.week}" ${i===0?'selected':''}>Week of ${x.week}${i===0?' — previous week':''}</option>`).join('');const show=wk=>{const x=older.find(r=>r.week===wk);if(x)$('wOldPhoto').src=URL.createObjectURL(x.blob)};show(older[0].week);$('wCompareSelect').onchange=e=>show(e.target.value)}
$('wPhoto').onchange=async e=>{const f=e.target.files&&e.target.files[0];if(!f)return;await putPhoto(f);await loadPhotoCompare()};
render();
})();